/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData home_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData man_user = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData phone_book = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData phone_book__1_ = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData qr_code__2_ = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calendar__1_ = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData calendar__2_ = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData notifications_button = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData qr_code__3_ = const IconData(0xe80b, fontFamily: _kFontFam);
}
